### ISSUE TITLE
If Statement Not Working

### ISSUE THREAD

**Issue by fineance** [dopevog/vython#1]
When I type ```if a > 18``` in the Vython terminal, I get this error saying:
```
NotDeclared : Variable is not declared.
 - Position : Lign 1 | Column 4
 - Name : a
 ```
Any idea why? Help please....

**Comment by dopevog** [comment]
Your error is simple. ```if``` statements don't work from the Vython terminal as their first line is incomplete. If you want to use an ```if``` statement, then you must create a script with a ```.vy``` extensions. Inside you will be able to add ```if``` statements. 
Example given below:
```
a = enter("Age: ")
a = int(a)
if a > 18
{
    show("Yes")
}
```

**Comment by dopevog** [comment]
Also, we are
